sudo: false
language: python
python:
  - '3.4'
addons:
  - postgresql: '9.3'
before_script:
  - psql -U postgres -c "create extension postgis"
cache:
  pip: true
  directories:
    - /home/travis/virtualenv
    - $HOME/.pip-cache/
    - $HOME/.tox/
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
  slack:
    secure: XDoMlbyJR1HOfF3ibOGNEizbb7MYGG8abDPrVTdTBscV5d3vm7qE0Uvd7Hq7YefwhSv8dJ+psrnWwMxBH7Z8zQmyLDyeVCNysOIfc3JfLi/cgrxZ0x0GoqUiiW8sgMl4Um/9jlEpcd5te5HpIeCFp0PHDO3GIWpzxx7xMbS6/0Q=
